# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/else/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/LED_flow/LED_flow.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_flow || ORIG_REF_NAME==LED_flow} -quiet] -quiet

# IP: bd/LED_flow/ip/LED_flow_pwm_generator_0_0/LED_flow_pwm_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_flow_pwm_generator_0_0 || ORIG_REF_NAME==LED_flow_pwm_generator_0_0} -quiet] -quiet

# IP: bd/LED_flow/ip/LED_flow_clk_divider_0_0/LED_flow_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_flow_clk_divider_0_0 || ORIG_REF_NAME==LED_flow_clk_divider_0_0} -quiet] -quiet

# IP: bd/LED_flow/ip/LED_flow_led_pwm_controller_0_0/LED_flow_led_pwm_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_flow_led_pwm_controller_0_0 || ORIG_REF_NAME==LED_flow_led_pwm_controller_0_0} -quiet] -quiet

# XDC: d:/working_soft/Xlinx_Vivado/project/SUCCESS1 - try/project_1.gen/sources_1/bd/LED_flow/LED_flow_ooc.xdc
